name: When Opened

on:
  pull_request_target:
    types:
    - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Checklist
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request_target'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Thank you for contributing to PlasmaPy! ✨ The project's future depends deeply on contributors like you, so we deeply appreciate it! 🌱 The following checklist can be used by you and the reviewer to help guide the code review process.

            - Overall
              - [ ] Does the PR do what it intends to do?
              - [ ] Except for very minor changes, is a changelog entry included and consistent with the [changelog guide](https://docs.plasmapy.org/en/latest/contributing/changelog_guide.html)?
              - [ ] Are the continuous integration checks passing? (Most linter problems can be automagically fixed by commenting on this PR with `pre-commit.ci autofix`.)
            - Code
              - [ ] Is new/updated code readable and consistent with the [coding guide](https://docs.plasmapy.org/en/latest/contributing/coding_guide.html)?
              - [ ] Can any large functions be split up into shorter functions that each do one thing?
              - [ ] Are SI units used?
            - Tests
              - [ ] Are tests added/updated as required, and consistent with the [testing guide](https://docs.plasmapy.org/en/latest/contributing/testing_guide.html)?
              - [ ] Are the tests understandable?
              - [ ] Do the tests cover all important cases?
            - Docs
              - [ ] Are docs added/updated as required, and consistent with the [doc guide](https://docs.plasmapy.org/en/latest/contributing/doc_guide.html)?
              - [ ] Are the docs understandable?
              - [ ] Do the docs show up correctly in the preview, including Jupyter notebooks?`
          })
