name: Check Pull Request Branch

on:
  pull_request:
    types: [opened]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check branch name
      id: check-branch-name
      run: |
        if [ ${{ github.event.pull_request.head.ref }} == "main" ]; then
          echo "Please do not create pull requests from the main branch of your fork. Create a new branch and make your changes there."
          echo "::set-env name=COMMENT_BODY::$(echo Please do not create pull requests from the main branch of your fork. Create a new branch and make your changes there.)"
        fi

    - name: Comment on pull request
      uses: actions/github-script@v6
      if: env.COMMENT_BODY
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '${{ env.COMMENT_BODY }}'
          })
