name: Manual Release Checklist Issue Creation

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Create Issue with Release Checklist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        checklist=$(sed "s/%VERSION%/${{ github.event.inputs.version }}/g" .github/checklists/release-checklist.md)
        gh issue create --title "Release Checklist for Version ${{ github.event.inputs.version }}" --body "$checklist"
