name: Comment on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = "Hello!";
            const prContext = github.context;
            const body = JSON.stringify({
              body: message
            });
            const requestOptions = {
              method: "POST",
              headers: {
                "Content-Type": "application/json",
                "User-Agent": "GitHub Actions"
              },
              body
            };
            const url = `https://api.github.com/repos/${prContext.repo.owner}/${prContext.repo.repo}/issues/${prContext.issue.number}/comments`;
            const response = await fetch(url, {
              ...requestOptions
            });
            console.log(response);

