name: New pull request

on:
  issues:
    types:
    - opened
  pull_request_target:
    types:
    - opened

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
    - name: 'Add checklist'
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request_target'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
	script: |
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Thank you for your contribution to Astropy!
            - [ ] Do the proposed changes actually accomplish desired goals?`
          })	  


