name: Label PR size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update_labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: PlasmaPy/action-size@v2023.5.0
      id: size
      with:
        size_xs_label: 'size: very small'
        size_s_label: 'size: small'
        size_m_label: 'size: medium'
        size_l_label: 'size: large'
        size_xl_label: 'size: very large'
        size_xxl_label: 'size: huge'
        size_s_threshold: 10
        size_m_threshold: 30
        size_l_threshold: 100
        size_xl_threshold: 500
        size_xxl_threshold: 1000

    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: ${{ steps.size.outputs.stale_labels }}

    - uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.github_token }}
        labels: ${{ steps.size.outputs.new_label }}
