name: Update pinned requirements

on:
  schedule:
    - cron: '0 1 * * 0' # This will run every Sunday at 1am UTC.
  workflow_dispatch:

jobs:
  update_requirements:
    runs-on: ubuntu-latest
    if: github.repository == 'namurphy/PlasmaPy'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Reset or create the branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin main:main
          git branch -D requirements-automatic-update || true
          git switch -C requirements-automatic-update main

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install pip-tools
        run: python -m pip install pip-tools

      - name: Generate requirements.txt
        run: pip-compile --all-extras --output-file=requirements.txt --resolver=backtracking -r -U

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update pinned requirements" || true

      - name: Push changes
        run: |
          git push -f origin requirements-automatic-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Update pinned requirements'
          body: 'This PR updates the pinned requirements based on the current state of the main branch.'
          base: 'main'
          head: 'requirements-automatic-update'
          labels: 'No changelog entry needed,dependencies'
          commit-message: 'Update pinned requirements'
          delete-branch: 'true'
