name: Update Requirements

on:
  workflow_dispatch:

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install pip-tools
        run: python -m pip install pip-tools

      - name: Configure Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Delete and recreate branch
        run: |
          git branch -D update-requirements || true
          git checkout -b update-requirements

      - name: Generate requirements.txt
        run: pip-compile --all-extras --output-file=requirements.txt --resolver=backtracking -r -U

      - name: Commit and push
        run: |
          git add requirements.txt
          git commit -m "Update requirements.txt"
          git push --force --set-upstream origin update-requirements

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update pinned requirements
          body: This PR updates the pinned requirements based on the current state of the main branch.
          labels: No changelog entry needed, dependencies
